# Generated by Django 5.1.5 on 2025-01-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='col',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='move',
            name='row',
        ),
    ]
